import {esc} from "../ui.js";
const fmt=a=>(a||[]).filter(Boolean).join(" / ")||"—";
function statusOf(x){return x.factAfter?`Факт ${x.factAfter}`:"ОЖИДАЕТ"}
function newCard(x){return `<details class="forecast-archive-card searchable-item" data-detail="${esc(x.detailFile||"")}"><summary><span><b>${esc(x.target?.date)} · ${esc(x.target?.time)}</b><small>CHAT MASTER · последний факт ${esc(x.lastFact||"—")}</small></span><strong>${esc(statusOf(x))}</strong></summary><div class="forecast-snapshot"><div><span>MASTER</span><b>${esc(fmt(x.master?.combos))}</b></div><div><span>Families</span><b>${esc(fmt(x.master?.families))}</b></div><div><span>MAIN</span><b>${esc(fmt((x.methods?.main?.top3||[]).map(v=>v.order)))}</b></div><div><span>Algorithm</span><b>${esc(fmt((x.methods?.algorithm?.top3||[]).map(v=>v.order)))}</b></div><div><span>APP CORE</span><b>${esc(x.methods?.appCore?.selected?.combo||"—")}</b></div><div><span>SHIFT</span><b>${esc(x.methods?.shift?.combo||"—")}</b></div><div><span>Зеркало · отдельно</span><b>${esc(fmt((x.mirror||[]).map(v=>v.triple||v)))}</b></div><div><span>Факт</span><b>${esc(x.factAfter||"ещё нет")}</b></div><div><span>Класс</span><b>${esc(x.audit?.classification||"—")}</b></div></div><div class="forecast-full-detail muted">Нажмите — загружается полный frozen…</div></details>`}
function legacyCard(x){return `<details class="forecast-archive-card searchable-item"><summary><span><b>${esc(x.target?.date)} · ${esc(x.target?.time)}</b><small>LEGACY до замены</small></span><strong>${esc(statusOf(x))}</strong></summary><div class="forecast-snapshot"><div><span>Статус</span><b>Старый прогноз сохранён только как история</b></div><div><span>Факт</span><b>${esc(x.factAfter||"—")}</b></div></div></details>`}
function fullDetail(d){
 const main=d.methods?.main||{},alg=d.methods?.algorithm||{},a=d.audit;
 return `<div class="full-forecast"><div class="section-title">CHAT MASTER FROZEN</div><div class="forecast-snapshot"><div><span>Создан</span><b>${esc(d.issuedAt||"—")}</b></div><div><span>Последний факт</span><b>${esc(d.lastFact||"—")}</b></div><div><span>MASTER</span><b>${esc(fmt(d.master?.combos))}</b></div><div><span>Families</span><b>${esc(fmt(d.master?.families))}</b></div><div><span>LAST Δ</span><b>${esc(main.signals?.seq?.signal||"—")}</b></div><div><span>TIME-DIRECTION</span><b>${esc(main.signals?.td?.signal||"—")}</b></div><div><span>MAIN</span><b>${esc(fmt((main.top3||[]).map(x=>x.order)))}</b></div><div><span>Algorithm</span><b>${esc(fmt((alg.top3||[]).map(x=>x.order)))}</b></div><div><span>APP CORE</span><b>${esc(d.methods?.appCore?.selected?.combo||"—")}</b></div><div><span>SHIFT</span><b>${esc(d.methods?.shift?.combo||"—")}</b></div><div><span>Факт</span><b>${esc(d.factAfter||"ещё нет")}</b></div><div><span>Аудит</span><b>${esc(a?.classification||"—")}</b></div></div>${a?`<div class="section-title">РАБОТА НАД ОШИБКОЙ</div><p>${esc(a.workError||"")}</p><p>RAW family: SEQ ${esc(a.main?.seq??0)} · TD ${esc(a.main?.td??0)} · assembly blind ${a.assemblyBlind?"ДА":"нет"}</p>`:""}</div>`;
}
export function renderArchive(ctx){
 const facts=[...ctx.records].slice(-500).reverse(),forecasts=[...(ctx.forecastIndex||[])].reverse(),hits=[...(ctx.state?.hitLog||[])].reverse(),audits=[...(ctx.state?.masterAudit||[])].reverse();
 return `<div class="card"><div class="card-head">АРХИВ · FROZEN / ФАКТ / РАБОТА НАД ОШИБКОЙ</div><div class="card-body"><div class="controls"><input id="archiveSearch" placeholder="Дата, время, комбинация, family"><button class="secondary" id="exportBtn">Экспорт архива</button></div><div class="archive-tabs"><button class="archive-tab active" data-atab="pred">ПРОГНОЗЫ</button><button class="archive-tab" data-atab="audit">АУДИТ</button><button class="archive-tab" data-atab="facts">ФАКТЫ</button><button class="archive-tab" data-atab="hits">HITS</button><button class="archive-tab" data-atab="mirror">ЗЕРКАЛО</button><button class="archive-tab" data-atab="system">СИСТЕМА</button></div>
 <section data-apanel="pred">${forecasts.map(x=>x.schema==="chat-master-v1"?newCard(x):legacyCard(x)).join("")||'<div class="tfc-empty">Архив пуст</div>'}</section>
 <section data-apanel="audit" hidden><div class="table-wrap"><table class="searchable"><thead><tr><th>Дата</th><th>Время</th><th>Факт</th><th>Family</th><th>MASTER</th><th>RAW</th><th>Класс</th><th>Assembly</th></tr></thead><tbody>${audits.map(a=>`<tr><td>${esc(a.date)}</td><td>${esc(a.time)}</td><td><b>${esc(a.fact)}</b></td><td>${esc(a.family)}</td><td>${a.master?.hit?"✅":"❌"}</td><td>${esc(a.main?.seq??0)} / ${esc(a.main?.td??0)}</td><td>${esc(a.classification)}</td><td>${a.assemblyBlind?"ДА":"нет"}</td></tr>`).join("")}</tbody></table></div></section>
 <section data-apanel="facts" hidden><div class="table-wrap"><table class="searchable"><thead><tr><th>Дата</th><th>Время</th><th>Тираж</th><th>Факт</th></tr></thead><tbody>${facts.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.time)}</td><td>${esc(r.draw||"—")}</td><td><b>${esc(r.combo)}</b></td></tr>`).join("")}</tbody></table></div></section>
 <section data-apanel="hits" hidden><div class="table-wrap"><table class="searchable"><thead><tr><th>Факт</th><th>Дата/время</th><th>Тип</th><th>Прогноз</th><th>Источник</th></tr></thead><tbody>${hits.flatMap(h=>(h.hits||[]).map(x=>`<tr><td>${esc(h.fact)}</td><td>${esc(h.date)} ${esc(h.time)}</td><td><b>${esc(x.type)}</b></td><td>${esc(x.combo)}</td><td>${esc(x.block)} ${esc(x.variant)}</td></tr>`)).join("")}</tbody></table></div></section>
 <section data-apanel="mirror" hidden><div class="table-wrap"><table class="searchable"><thead><tr><th>Дата/время</th><th>Факт</th><th>Тройник</th><th>База</th><th>Permutation</th></tr></thead><tbody>${mirrorHits.map(h=>`<tr><td>${esc(h.date)} ${esc(h.time)}</td><td><b>${esc(h.fact)}</b></td><td>${esc(h.triple)}</td><td>${esc(h.base)}</td><td>${esc(h.permutation)}</td></tr>`).join("")||'<tr><td colspan="5">Попаданий зеркала нет.</td></tr>'}</tbody></table></div></section><section data-apanel="system" hidden><div class="system-log">${[...(ctx.state?.systemLog||[])].reverse().map(x=>`<div class="tfc-row"><span>${esc(x.at)}</span><b>${esc(x.msg)}</b></div>`).join("")}</div></section></div></div>`;
}
export function mountedArchive(ctx){
 document.querySelectorAll(".archive-tab").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".archive-tab").forEach(x=>x.classList.toggle("active",x===btn));document.querySelectorAll("[data-apanel]").forEach(p=>p.hidden=p.dataset.apanel!==btn.dataset.atab)});
 const inp=document.querySelector("#archiveSearch");if(inp)inp.oninput=()=>{const q=inp.value.toLowerCase();document.querySelectorAll(".searchable tbody tr,.searchable-item").forEach(el=>{el.style.display=el.textContent.toLowerCase().includes(q)?"":"none"})};
 document.querySelectorAll(".forecast-archive-card[data-detail]").forEach(d=>d.addEventListener("toggle",async()=>{if(!d.open||d.dataset.loaded==="1")return;d.dataset.loaded="1";const target=d.querySelector(".forecast-full-detail"),file=d.dataset.detail;if(!file)return;try{const r=await fetch("./"+file+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);target.classList.remove("muted");target.innerHTML=fullDetail(await r.json())}catch(e){target.textContent="Не удалось загрузить: "+e.message}}));
 const e=document.querySelector("#exportBtn");if(e)e.onclick=()=>{const blob=new Blob([JSON.stringify({facts:ctx.records,forecasts:ctx.forecastIndex||[],masterAudit:ctx.state?.masterAudit||[],mirrorAudit:ctx.state?.mirrorAudit||[],mirrorHitLog:ctx.state?.mirrorHitLog||[],hits:ctx.state?.hitLog||[],observations:ctx.state?.observations||[],systemLog:ctx.state?.systemLog||[]},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="top3-chat-master-full-archive.json";a.click();URL.revokeObjectURL(a.href)};
}
